# start_patroni.yml

- name: Reload systemd to apply new unit file
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Patroni service on node01
  ansible.builtin.systemd:
    name: patroni
    enabled: true
    state: started
  when: inventory_hostname == "node01"

- name: Wait for Patroni service to be up on node01
  ansible.builtin.wait_for:
    port: 8008 # Adjust this to the actual Patroni REST API port
    host: "{{ ansible_host }}"
    timeout: 300
  when: inventory_hostname == "node01"

# Run each task one-by-one using delegate_to
- name: Enable and start Patroni service on remaining nodes
  ansible.builtin.systemd:
    name: patroni
    enabled: true
    state: started
  delegate_to: "{{ item }}"
  run_once: true
  with_items: "{{ groups['patroni'] | difference(['node01']) }}"
  when: inventory_hostname == "node01"

- name: Wait for Patroni service to be up on remaining nodes
  ansible.builtin.wait_for:
    port: 8008 # Adjust this to the actual Patroni REST API port
    host: "{{ item }}"
    timeout: 300
  delegate_to: "{{ item }}"
  run_once: true
  with_items: "{{ groups['patroni'] | difference(['node01']) }}"
  when: inventory_hostname == "node01"
